Dr. Silva's Likes - by Chris Grant

 The hypothesis I drew from Dr. Silva's likes was that he would use social media in different ways from younger generations (I promise I am not calling you old). I would say that people from my generation use social media incessantly. We are more likely to use them for longer periods of time, so we have more interactions than older social media users. Through Dr. Silva's likes, I can present a case for this. In theory, I will be able to conclude that older generations do in fact use social media differently than younger generations. Statistically, looking through user interactions in the form of likes can provide proof of this.

The data provided in the json file is an appropriate test for my hypothesis because it is a social media feature that is the most common interaction made on those platforms.

The "people" who collected this data is the corporate entity / shadow government, Meta. This data was collected to record user interactions on their website. This is valuable to them for many reasons, including advertising. This data may be reliable to form a hypothesis such as mine, or for Meta to figure out what things you might like advertised to you. This data could be unreliable due to the sometimes sporadic nature of social media interactions. Dr. Silva could have liked a post on accident, may have seen a pretty painting sent to him by another user via messages, or saw a funny video on his explore page.

In [3]:
import pandas as pd
import json

In [5]:
with open(r"C:\Users\chris\Downloads\drive-download-20230912T152207Z-001\technogecko_20200714_toshare\likes.json") as cm:
    likes = json.load(cm)

In [6]:
liked_posts = pd.DataFrame(likes['media_likes'])

In [19]:
liked_posts.iloc[0:100].sort_values(1, ascending = False).groupby(1).count()

                   0
1
ali_saurusrex     18
aroseroar16        4
athenalemon        1
ball_doesnt_lie    2
cacandassociates  15
catsandkilos       1
cbarker13          7
colin_storm        7
danneabreanne      2
drchadlarson       3
emmyr0o            6
inalull           10
jackie.cc          1
jennjohnn          2
leleebabe          3
miles_sari         2
mtb_crohnert92     1
mycaninelife       1
orangekoala2       2
poorlydrawnlines   2
reams_esq          4
samuel.rhodes      1
shaunacoxsey       1
silva_c097         3
sp4zie             1

The dataset above shows a total of 100 likes made by Dr. Silva. These 100 likes are the first 100 indexed from Dr. Silva's account. From this, we are able to infer who's accounts may have the most likes from Dr. Silva in the future. The outliers in this dataset will prove to be the accounts with the most interaction, potential favorite accounts or close friends, and with the least interaction, potential mutual friends.

In [21]:
my_list = [x[1] for x in (likes['media_likes'])]

In [30]:
total_list = pd.DataFrame(my_list)
total_list.head(50)

                   0
0    ball_doesnt_lie
1    ball_doesnt_lie
2      ali_saurusrex
3   cacandassociates
4   cacandassociates
5          reams_esq
6            emmyr0o
7      ali_saurusrex
8        colin_storm
9      ali_saurusrex
10       colin_storm
11           emmyr0o
12           emmyr0o
13  cacandassociates
14           inalull
15         reams_esq
16           inalull
17           emmyr0o
18           inalull
19  cacandassociates
20           inalull
21         jennjohnn
22  cacandassociates
23     ali_saurusrex
24  cacandassociates
25  cacandassociates
26  cacandassociates
27           inalull
28  cacandassociates
29     ali_saurusrex
30           inalull
31  cacandassociates
32  poorlydrawnlines
33       athenalemon
34           inalull
35      orangekoala2
36  cacandassociates
37      mycaninelife
38     ali_saurusrex
39         reams_esq
40  cacandassociates
41           inalull
42     ali_saurusrex
43           emmyr0o
44     ali_saurusrex
45           inalull
46         reams_esq
47         leleebabe
48           inalull
49     ali_saurusrex

This dataset shows the first 50 likes by Dr. Silva. As opposed to the other data set, we can see the order in which these likes happened.

There were a few limitations in the data provided by Meta. For example, if there was a way to identify what kind of post was liked, we could draw other inferences about this dataset. When Meta collects data on what and who's posts are liked by users, it could have another form of information attached to it that could give analysts an insight on what picture the user could have been seeing. If it was a picture of an outdoor setting, an outdoor tag could be used for example. They could utilize their existing hashtag system and if a user creates a post with a key-worded hashtag, they could capture that data as well. Potential next steps with this data I analyzed could be comparing it to a peer's Meta data. With this, we could further reinforce my hypothesis or deflate it.